import {spawn} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {afterAll,describe,it,expect} from 'vitest';
import {randomUUID} from 'node:crypto';
import request from 'supertest';
import {pool,transaction} from '@tipkhun/database';
import {app} from './server.js';
const suite=process.env.RUN_DB_TESTS==='1'?describe:describe.skip;
suite('Real Gateway/Auth/Trading/Risk/PostgreSQL/PaperBroker',()=>{
 afterAll(()=>pool.end());
 async function fixture(limits:Record<string,unknown>={}){
  const email=`paper-${randomUUID()}@example.test`,password='Paper-password-1234';
  expect((await request(app).post('/api/v1/auth/register').send({email,password})).status).toBe(201);
  const l=await request(app).post('/api/v1/auth/login').send({email,password});const token=l.body.accessToken,id=l.body.user.id;
  const api=(method:'get'|'post'|'put',path:string)=>request(app)[method](`/api/v1${path}`).set('Authorization',`Bearer ${token}`);
  await api('put','/risk/profile').send({riskTolerance:1000,dailyLossLimit:'5000',riskPerTrade:'1000',maxTrades:20,maxPositions:20,maxDrawdown:10000});
  await api('post','/plans').send({capitalMinor:'100000',dailyLossLimitMinor:'5000',riskPerTradeMinor:'1000',maxTrades:20,...limits});
  const started=await api('post','/bot/start').send({});expect(started.status).toBe(200);
  const order=(quantity='1',scenario='fill',key=randomUUID())=>api('post','/orders').set('Idempotency-Key',key).send({instrument:'SYNTHETIC-THB',quantity,type:'MARKET',scenario});
  return {api,order,id,accountId:started.body.paperAccountId,token};
 }
 it('approved order opens real persisted paper position with fees and no fabricated gain',async()=>{
  const f=await fixture();const o=await f.order();expect(o.status).toBe(201);expect(o.body.state).toBe('FILLED');
  const s=await f.api('get','/bot/status');expect(s.body.account).toMatchObject({cashMinor:'99898',equityMinor:'99999',feesMinor:'1'});expect(s.body.liveTrading).toBe('LOCKED');
  expect((await f.api('get','/risk/status')).body.riskReservedMinor).toBe('103');
  expect((await f.api('post','/reconcile').send({})).body.status).toBe('OK');
  const p=(await f.api('get','/positions')).body[0];const closed=await f.api('post',`/positions/${p.id}/close`).send({});expect(closed.body.net_pnl_minor).toBe('-4');
  expect((await f.api('get','/risk/status')).body.riskUsedMinor).toBe('4');expect((await f.api('post','/reconcile').send({})).body.status).toBe('OK');
 });
 it('per-trade server risk rejects and client cannot override limits',async()=>{const f=await fixture({riskPerTradeMinor:'100'});const o=await f.order();expect(o.body.state).toBe('REJECTED');expect(o.body.reject_reason).toContain('per-trade');expect((await f.api('post','/orders').set('Idempotency-Key',randomUUID()).send({instrument:'SYNTHETIC-THB',quantity:'1',type:'MARKET',capitalMinor:'999999'})).status).toBe(400);});
 it('atomic concurrent reservations never overdraw budget',async()=>{const f=await fixture({dailyLossLimitMinor:'150',riskPerTradeMinor:'150'});const result=await Promise.all([f.order(),f.order()]);expect(result.map(r=>r.body.state).sort()).toEqual(['FILLED','REJECTED']);expect((await f.api('get','/risk/status')).body.riskReservedMinor).toBe('103');});
 it('idempotent concurrent retries fill once and reject different payload',async()=>{const f=await fixture();const key=randomUUID();const rs=await Promise.all([f.order('1','fill',key),f.order('1','fill',key)]);expect(rs[0].body.id).toBe(rs[1].body.id);expect((await f.api('get','/positions')).body).toHaveLength(1);expect((await f.order('2','fill',key)).status).toBe(409);});
 it('max trade slots cannot be bypassed by closing positions',async()=>{const f=await fixture({maxTrades:1});await f.order();const p=(await f.api('get','/positions')).body[0];await f.api('post',`/positions/${p.id}/close`).send({});expect((await f.order()).body.reject_reason).toBe('Maximum trades reached');});
 it('daily realized loss stops new orders',async()=>{const f=await fixture({dailyLossLimitMinor:'103',riskPerTradeMinor:'103'});await pool.query("INSERT INTO trades(account_id,net_pnl_minor,fees_minor,mode) VALUES($1,-103,0,'paper')",[f.accountId]);expect((await f.order()).body.reject_reason).toBe('Daily loss limit reached');});
 it('partial fill, continue and explicit close preserve exact balances',async()=>{const f=await fixture();const o=await f.order('4','partial');expect(o.body.state).toBe('PARTIALLY_FILLED');expect(o.body.filled_quantity).toBe('2');const next=await f.api('post',`/orders/${o.body.id}/continue`).send({});expect(next.body.state).toBe('FILLED');expect(next.body.filled_quantity).toBe('4');expect((await f.api('post','/reconcile').send({})).body.status).toBe('OK');});
 it('cancel partially filled remainder retains position risk until explicit close',async()=>{const f=await fixture();const o=await f.order('4','partial');expect((await f.api('post',`/orders/${o.body.id}/cancel`).send({})).body.state).toBe('CANCELLED');expect((await f.api('get','/risk/status')).body.riskReservedMinor).toBe('206');const p=(await f.api('get','/positions')).body[0];await f.api('post',`/positions/${p.id}/close`).send({});expect((await f.api('get','/risk/status')).body.riskReservedMinor).toBe('0');expect((await f.api('post','/reconcile').send({})).body.status).toBe('OK');});
 it('broker reject releases reservation',async()=>{const f=await fixture();expect((await f.order('1','reject')).body.state).toBe('REJECTED');expect((await f.api('get','/risk/status')).body.riskReservedMinor).toBe('0');});
 it('broker error retains reservation and requires reconciliation',async()=>{const f=await fixture();expect((await f.order('1','error')).status).toBe(503);expect((await f.api('get','/orders')).body[0].state).toBe('UNKNOWN');expect((await f.api('get','/bot/status')).body.brokerStatus).toBe('RECONCILIATION_REQUIRED');expect((await f.order()).status).toBe(409);});
 it('unknown outcome is never guessed or released',async()=>{const f=await fixture();const o=await f.order('1','unknown');expect(o.body.state).toBe('UNKNOWN');expect((await f.api('post',`/orders/${o.body.id}/cancel`).send({})).status).toBe(409);expect((await f.api('get','/risk/status')).body.riskReservedMinor).toBe('103');});
 it('reconciliation recovers an unknown outcome once broker evidence appears',async()=>{const f=await fixture();const o=await f.order('1','unknown');await pool.query("INSERT INTO paper_broker_orders(order_id,state,filled_quantity) VALUES($1,'FILLED',1)",[o.body.id]);await pool.query("INSERT INTO paper_broker_fills(order_id,side,quantity,price_minor,fee_minor) VALUES($1,'BUY',1,101,1)",[o.body.id]);const check=await pool.query('SELECT id,state FROM orders WHERE id=$1',[o.body.id]);expect(check.rowCount).toBe(1);const rec=await f.api('post','/reconcile').send({});expect(rec.body.status).toBe('OK');expect((await f.api('get',`/orders/${o.body.id}`)).body.state).toBe('FILLED');expect((await f.api('get','/positions')).body.some((p:any)=>p.order_id===o.body.id)).toBe(true);});
 it('emergency stop races against order and latches against future/AI entries',async()=>{const f=await fixture();await Promise.all([f.order('4','partial'),f.api('post','/bot/emergency-stop').send({})]);expect((await f.api('get','/bot/status')).body.state).toBe('EMERGENCY_STOPPED');expect((await f.order()).status).toBe(409);expect((await f.api('post','/bot/resume').send({})).status).toBe(409);const pending=(await f.api('get','/orders')).body.filter((o:any)=>['RISK_CHECKED','SUBMITTED','PARTIALLY_FILLED'].includes(o.state));expect(pending).toHaveLength(0);});
 it('pause/resume/stop transitions are validated',async()=>{const f=await fixture();expect((await f.api('post','/bot/pause').send({})).body.state).toBe('PAUSED');expect((await f.order()).status).toBe(409);expect((await f.api('post','/bot/resume').send({})).body.state).toBe('RUNNING');expect((await f.api('post','/bot/stop').send({})).body.state).toBe('STOPPED');expect((await f.api('post','/bot/resume').send({})).status).toBe(409);});
 it('reconciliation detects corrupted balance and stops new orders',async()=>{const f=await fixture();await f.order();await pool.query('UPDATE accounts SET cash_minor=cash_minor+1 WHERE id=$1',[f.accountId]);expect((await f.api('post','/reconcile').send({})).body.status).toBe('RECONCILIATION_REQUIRED');expect((await f.order()).status).toBe(409);});
 it('ownership and authentication deny foreign orders/accounts',async()=>{const f=await fixture();const o=await f.order();expect((await request(app).get(`/api/v1/orders/${o.body.id}`)).status).toBe(401);const stranger=await fixture();expect((await stranger.api('get',`/orders/${o.body.id}`)).status).toBe(404);expect((await stranger.api('post',`/orders/${o.body.id}/cancel`).send({})).status).toBe(404);expect((await stranger.api('post','/orders').set('Idempotency-Key',randomUUID()).send({instrument:'SYNTHETIC-THB',quantity:'1',type:'MARKET',accountId:f.accountId})).status).toBe(400);});
 it('database rollback does not leak partial balance updates',async()=>{const row=(await pool.query("SELECT id,cash_minor FROM accounts WHERE environment='paper' LIMIT 1")).rows[0];await expect(transaction(async c=>{await c.query('UPDATE accounts SET cash_minor=cash_minor+777 WHERE id=$1',[row.id]);throw new Error('rollback');})).rejects.toThrow('rollback');expect((await pool.query('SELECT cash_minor FROM accounts WHERE id=$1',[row.id])).rows[0].cash_minor).toBe(row.cash_minor);});
 it('database blocks lifecycle skips',async()=>{const o=(await pool.query("SELECT id FROM orders WHERE state='REJECTED' AND paper_order LIMIT 1")).rows[0];await expect(pool.query("UPDATE orders SET state='FILLED' WHERE id=$1",[o.id])).rejects.toThrow('Invalid paper order transition');});
 it('restart recovers persisted orders, positions and balances',async()=>{
 const f=await fixture();const order=await f.order();
 async function run(){const child=spawn(process.execPath,[fileURLToPath(new URL('../../trading-service/dist/server.js',import.meta.url))],{env:{...process.env,NODE_ENV:'development',TRADING_PORT:'13004'},stdio:'ignore'});let ready=false;for(let i=0;i<40;i++){try{if((await fetch('http://127.0.0.1:13004/ready')).ok){ready=true;break;}}catch{}await new Promise(r=>setTimeout(r,50));}expect(ready).toBe(true);return child;}
 let child=await run();const first=await fetch('http://127.0.0.1:13004/v1/bot/status',{headers:{authorization:`Bearer ${f.token}`}}).then(r=>r.json());await new Promise<void>(resolve=>{child.on('exit',()=>resolve());child.kill('SIGTERM');});
 child=await run();try{const second=await fetch('http://127.0.0.1:13004/v1/bot/status',{headers:{authorization:`Bearer ${f.token}`}}).then(r=>r.json());expect(second.account).toEqual(first.account);expect(second.brokerStatus).toBe('PAPER_CONNECTED');expect((await f.api('get',`/orders/${order.body.id}`)).body.state).toBe('FILLED');}finally{await new Promise<void>(resolve=>{child.on('exit',()=>resolve());child.kill('SIGTERM');});}
 },15000);
 it('audit covers paper lifecycle without credentials',async()=>{const rows=(await pool.query("SELECT action FROM audit_logs WHERE action IN ('BOT_STARTED','BOT_PAUSED','BOT_RESUMED','BOT_STOPPED','EMERGENCY_STOP','ORDER_CREATED','ORDER_APPROVED','ORDER_REJECTED','ORDER_FILLED','POSITION_OPENED','POSITION_CLOSED') GROUP BY action")).rows;expect(rows).toHaveLength(11);});
 it('ledger and profit router use realized paper profit exactly once',async()=>{const f=await fixture();const o=await f.order();const p=(await f.api('get','/positions')).body[0];await f.api('post',`/positions/${p.id}/close`).send({});const summary=await f.api('get','/ledger/summary');expect(summary.status).toBe(200);expect(summary.body.buckets.REALIZED_PROFIT).toBe('-4');const preview=await f.api('post','/allocations/preview').send({});expect(preview.body.amountMinor).toBe('0');expect((await f.api('post','/allocations/confirm').set('Idempotency-Key',randomUUID()).send({})).status).toBe(409);});
 it('profitable test-only close derives net profit from fills and routes it once',async()=>{const f=await fixture();const o=await f.order('1','profit');const p=(await f.api('get','/positions')).body[0];const closed=await f.api('post',`/positions/${p.id}/close`).send({});expect(closed.body.net_pnl_minor).toBe('17');const before=(await f.api('get','/ledger/summary')).body.buckets.REALIZED_PROFIT;const previews=await Promise.all(Array.from({length:10},()=>f.api('post','/allocations/preview').send({})));expect(previews.every(x=>x.body.amountMinor==='17')).toBe(true);expect((await f.api('get','/ledger/summary')).body.buckets.REALIZED_PROFIT).toBe(before);const a=await f.api('get','/allocations/available');expect(a.body.availableMinor).toBe('17');const preview=await f.api('post','/allocations/preview').send({});expect(preview.body).toMatchObject({shortTermMinor:'8',longTermMinor:'5',withdrawalMinor:'4'});const key=randomUUID(),confirmed=await f.api('post','/allocations/confirm').set('Idempotency-Key',key).send({});expect(confirmed.status).toBe(201);const retry=await f.api('post','/allocations/confirm').set('Idempotency-Key',key).send({});expect(retry.body.id).toBe(confirmed.body.id);expect((await f.api('get','/allocations/available')).body.availableMinor).toBe('0');expect((await f.api('get','/portfolio/cash')).body.longTermReservedCashMinor).toBe('5');expect((await f.api('get','/withdrawals/reserve')).body.withdrawalReservedMinor).toBe('4');expect((await f.api('get','/allocations/history')).body).toHaveLength(1);});
 it('equal entry and exit produces fee-only loss',async()=>{const f=await fixture();await f.order('1','even');const p=(await f.api('get','/positions')).body[0];const closed=await f.api('post',`/positions/${p.id}/close`).send({});expect(closed.body.net_pnl_minor).toBe('-2');});
 it('concurrent allocation confirms cannot consume profit twice',async()=>{const f=await fixture();await f.order('1','profit');const p=(await f.api('get','/positions')).body[0];await f.api('post',`/positions/${p.id}/close`).send({});const r=await Promise.all([f.api('post','/allocations/confirm').set('Idempotency-Key',randomUUID()).send({}),f.api('post','/allocations/confirm').set('Idempotency-Key',randomUUID()).send({})]);expect(r.filter(x=>x.status===201)).toHaveLength(1);expect((await f.api('get','/allocations/available')).body.availableMinor).toBe('0');});
});
