import {spawn} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {randomUUID} from 'node:crypto';
import {describe,it,expect,afterAll} from 'vitest';
import {pool,transaction} from '@tipkhun/database';
const base='http://127.0.0.1:13000/api/v1';
if(process.env.RUN_DB_TESTS!=='1')throw new Error('Run with tool/integration.mjs portfolio');
type Api=(method:string,path:string,body?:unknown,key?:string)=>Promise<{status:number;body:any}>;
async function request(token:string,method:string,path:string,body?:unknown,key?:string){const r=await fetch(base+path,{method,headers:{'content-type':'application/json',authorization:`Bearer ${token}`,...(key?{'Idempotency-Key':key}:{})},body:body===undefined?undefined:JSON.stringify(body)});return {status:r.status,body:r.status===204?null:await r.json()};}
async function fixture(funded=true){
 const email=`portfolio-${randomUUID()}@example.test`,password='Portfolio-password-1234';
 expect((await request('','POST','/auth/register',{email,password})).status).toBe(201);
 const login=await request('','POST','/auth/login',{email,password}),token=login.body.accessToken,id=login.body.user.id;
 const api:Api=(m,p,b,k)=>request(token,m,p,b,k);
 expect((await api('PUT','/risk/profile',{riskTolerance:1000,dailyLossLimit:'5000',riskPerTrade:'2000',maxTrades:20,maxPositions:20,maxDrawdown:10000})).status).toBe(200);
 expect((await api('POST','/plans',{capitalMinor:'100000',dailyLossLimitMinor:'5000',riskPerTradeMinor:'2000',maxTrades:20})).status).toBe(201);
 expect((await api('POST','/bot/start',{})).status).toBe(200);
 const trade=await api('POST','/orders',{instrument:'SYNTHETIC-THB',type:'MARKET',quantity:'10',scenario:'profit101'},randomUUID());expect(trade.body.state).toBe('FILLED');
 const position=(await api('GET','/positions')).body[0];
 const closed=await api('POST',`/positions/${position.id}/close`,{});expect(closed.body.net_pnl_minor).toBe('1025');
 expect((await api('POST','/allocations/confirm',{},randomUUID())).status).toBe(201);
 expect((await api('GET','/portfolio/cash')).body.longTermReservedCashMinor).toBe('307');
 if(funded)expect((await api('POST','/portfolio/fund',{amountMinor:'300'},randomUUID())).status).toBe(201);
 const order=(side='BUY',quantity='10',key=randomUUID(),symbol='PTT')=>api('POST','/portfolio/orders',{side,quantity,symbol},key);
 const scenario=(scenario:string)=>api('PUT','/market/test-scenario',{symbol:'PTT',scenario});
 return {api,order,scenario,id,token};
}
describe('Phase 5 real HTTP Gateway/Auth/Risk/Trading/Allocation/Portfolio/PostgreSQL',()=>{
 afterAll(()=>pool.end());
 it('full profitable trading → allocation → funding → BUY → valuation → SELL → snapshots ledger flow',async()=>{
  const f=await fixture();const fund=(await f.api('GET','/portfolio/funding-history')).body;expect(fund).toHaveLength(1);
  expect((await f.api('GET','/market/quotes/PTT')).body).toMatchObject({priceMinor:'10',source:'deterministic-paper',isStale:false});
  const before=(await f.api('GET','/ledger/transactions')).body.length;
  const preview=await f.api('POST','/portfolio/orders/preview',{side:'BUY',symbol:'PTT',quantity:'10'});expect(preview.body).toMatchObject({amountMinor:'100',feeMinor:'1',cashAfterMinor:'199'});expect((await f.api('GET','/ledger/transactions')).body).toHaveLength(before);
  const buy=await f.order();expect(buy.status).toBe(201);expect(buy.body.cost_minor).toBe('101');
  await f.scenario('up');const valued=(await f.api('GET','/portfolio')).body;expect(valued).toMatchObject({cashMinor:'199',marketValueMinor:'120',totalValueMinor:'319',unrealizedPnlMinor:'19'});
  const sell=await f.order('SELL');expect(sell.status).toBe(201);expect(sell.body.realized_pnl_minor).toBe('18');
  const final=(await f.api('GET','/portfolio')).body;expect(final).toMatchObject({cashMinor:'318',marketValueMinor:'0',realizedPnlMinor:'18',reconciliationStatus:'OK',returnBps:600});expect(final.holdings).toHaveLength(0);
  const ledger=(await f.api('GET','/ledger/summary')).body.buckets;expect(ledger).toMatchObject({LONG_TERM_RESERVE:'7',PORTFOLIO_CASH:'318',PORTFOLIO_COST:'0',PORTFOLIO_PNL:'-18'});
  expect((await f.api('GET','/portfolio/performance')).body.length).toBeGreaterThan(0);
  const balance=(await pool.query("SELECT t.id,sum(CASE WHEN e.direction='DEBIT' THEN e.amount_minor ELSE -e.amount_minor END)::text AS n FROM ledger_transactions t JOIN ledger_entries e ON e.transaction_id=t.id WHERE t.user_id=$1 GROUP BY t.id",[f.id])).rows;expect(balance.every(r=>r.n==='0')).toBe(true);
 },15000);
 it('funding cannot exceed reserve and duplicate funding is atomic',async()=>{const f=await fixture(false);expect((await f.api('POST','/portfolio/fund',{amountMinor:'308'},randomUUID())).status).toBe(409);const key=randomUUID(),rs=await Promise.all([f.api('POST','/portfolio/fund',{amountMinor:'300'},key),f.api('POST','/portfolio/fund',{amountMinor:'300'},key)]);expect(rs.every(r=>r.status===201)).toBe(true);expect(rs[0].body.id).toBe(rs[1].body.id);expect((await f.api('POST','/portfolio/fund',{amountMinor:'301'},key)).body.error).toBe('IDEMPOTENCY_CONFLICT');expect((await f.api('GET','/portfolio/cash')).body.cashMinor).toBe('300');});
 it('concurrent BUY never overspends cash',async()=>{const f=await fixture();const rs=await Promise.all([f.order('BUY','20'),f.order('BUY','20')]);expect(rs.map(r=>r.status).sort()).toEqual([201,409]);expect((await f.api('GET','/portfolio/cash')).body.cashMinor).toBe('99');});
 it('duplicate concurrent order fills once and rejects changed meaning',async()=>{const f=await fixture(),key=randomUUID(),rs=await Promise.all([f.order('BUY','10',key),f.order('BUY','10',key)]);expect(rs[0].body.id).toBe(rs[1].body.id);expect((await f.order('BUY','11',key)).status).toBe(409);expect((await f.api('GET','/portfolio/orders')).body).toHaveLength(1);});
 it('cannot sell absent or insufficient holdings; cannot inject client financial state',async()=>{const f=await fixture();expect((await f.order('SELL')).body.error).toBe('INSUFFICIENT_HOLDINGS');expect((await f.api('POST','/portfolio/orders',{side:'BUY',symbol:'PTT',quantity:'1',cash:'999999',priceMinor:'1'},randomUUID())).status).toBe(400);expect((await f.order('BUY','100')).body.error).toBe('INSUFFICIENT_CASH');});
 it('weighted average basis, fractional liquidation, fees and deterministic loss',async()=>{const f=await fixture();await f.order('BUY','3');await f.scenario('up');await f.order('BUY','2');const h=(await f.api('GET','/portfolio/holdings')).body[0];expect(h.costBasisMinor).toBe('56');await f.scenario('down');const sold=await f.order('SELL','1.5');expect(sold.body).toMatchObject({amount_minor:'12',fee_minor:'1',cost_minor:'16',realized_pnl_minor:'-5'});const rest=await f.order('SELL','3.5');expect(rest.body.cost_minor).toBe('40');expect((await f.api('GET','/portfolio')).body.reconciliationStatus).toBe('OK');});
 it('unchanged price realizes fee-only loss',async()=>{const f=await fixture();await f.order();expect((await f.order('SELL')).body.realized_pnl_minor).toBe('-2');});
 it('stale and unavailable provider cannot mutate cash or holdings; delayed fresh price accepted',async()=>{const f=await fixture();await f.scenario('stale');expect((await f.order()).body.error).toBe('MARKET_DATA_STALE');await f.scenario('unavailable');expect((await f.order()).body.error).toBe('MARKET_DATA_UNAVAILABLE');expect((await f.api('GET','/portfolio/cash')).body.cashMinor).toBe('300');expect((await f.api('GET','/portfolio/orders')).body).toHaveLength(0);await f.scenario('delayed');expect((await f.api('GET','/market/quotes/PTT')).body.isDelayed).toBe(true);expect((await f.order()).status).toBe(201);});
 it('target allocations validate total, assets and show deviation; watchlist uses server quotes',async()=>{const f=await fixture();expect((await f.api('PUT','/portfolio/targets',{targets:[{target:'CASH',weightBps:9999}]})).status).toBe(400);expect((await f.api('PUT','/portfolio/targets',{targets:[{target:'FAKE',weightBps:10000}]})).status).toBe(404);expect((await f.api('PUT','/portfolio/targets',{targets:[{target:'CASH',weightBps:1000},{target:'PTT',weightBps:9000}]})).status).toBe(200);expect((await f.api('GET','/portfolio/targets')).body.find((t:any)=>t.target==='CASH').differenceBps).toBe(9000);expect((await f.api('POST','/watchlist',{symbol:'TDEX'})).status).toBe(201);expect((await f.api('GET','/watchlist')).body[0].quote.priceMinor).toBe('20');await f.api('DELETE','/watchlist/TDEX');expect((await f.api('GET','/watchlist')).body).toHaveLength(0);});
 it('owner isolation: foreign portfolio IDs cannot redirect read/fund/order/targets/watchlist',async()=>{const a=await fixture(),b=await fixture(false);await a.order();expect((await request('','GET','/portfolio')).status).toBe(401);expect((await b.api('GET',`/portfolio/holdings?userId=${a.id}`)).body).toHaveLength(0);expect((await b.api('GET','/portfolio/cash')).body.cashMinor).toBe('0');expect((await b.api('POST','/portfolio/fund',{amountMinor:'1',userId:a.id},randomUUID())).status).toBe(400);expect((await b.api('GET','/ledger/transactions')).body.every((t:any)=>t.user_id===b.id)).toBe(true);});
 it('ledger and transaction history are immutable, unbalanced transaction rejected and rolled back',async()=>{const f=await fixture();const t=(await f.api('GET','/portfolio/funding-history')).body[0];await expect(pool.query('UPDATE ledger_entries SET amount_minor=amount_minor+1 WHERE transaction_id=$1',[t.ledger_transaction_id])).rejects.toThrow('immutable');await expect(pool.query('DELETE FROM ledger_entries WHERE transaction_id=$1',[t.ledger_transaction_id])).rejects.toThrow('immutable');await expect(pool.query('UPDATE portfolio_transactions SET amount_minor=1 WHERE id=$1',[t.id])).rejects.toThrow('immutable');await expect(pool.query('UPDATE ledger_transactions SET reference_entity=$2 WHERE id=$1',[t.ledger_transaction_id,'changed'])).rejects.toThrow('immutable');await expect(pool.query('INSERT INTO ledger_entries(transaction_id,ledger_account_id,direction,amount_minor) SELECT transaction_id,ledger_account_id,direction,amount_minor FROM ledger_entries WHERE transaction_id=$1 LIMIT 1',[t.ledger_transaction_id])).rejects.toThrow('sealed');const id=randomUUID();await expect(transaction(async c=>{await c.query("INSERT INTO ledger_transactions(id,user_id,transaction_type,idempotency_key) VALUES($1,$2,'PORTFOLIO_BUY',$3)",[id,f.id,randomUUID()]);})).rejects.toThrow('Unbalanced');expect((await pool.query('SELECT id FROM ledger_transactions WHERE id=$1',[id])).rowCount).toBe(0);});
 it('mismatched projection latches without silent repair and blocks new orders',async()=>{const f=await fixture();const p=(await f.api('GET','/portfolio/cash')).body.portfolioId;await pool.query('UPDATE portfolio_cash SET amount_minor=amount_minor+1 WHERE portfolio_id=$1',[p]);expect((await f.order()).body.error).toBe('RECONCILIATION_REQUIRED');expect((await f.api('GET','/portfolio')).body.reconciliationStatus).toBe('RECONCILIATION_REQUIRED');expect((await f.api('GET','/portfolio/cash')).body.cashMinor).toBe('301');const events=(await pool.query("SELECT id FROM notifications WHERE user_id=$1 AND event_type='LEDGER_RECONCILIATION_REQUIRED'",[f.id])).rows;expect(events).toHaveLength(1);});
 it('concurrent funding cannot spend the same reserve twice',async()=>{const f=await fixture(false);const rs=await Promise.all([f.api('POST','/portfolio/fund',{amountMinor:'200'},randomUUID()),f.api('POST','/portfolio/fund',{amountMinor:'200'},randomUUID())]);expect(rs.map(r=>r.status).sort()).toEqual([201,409]);expect((await f.api('GET','/portfolio/cash')).body).toMatchObject({cashMinor:'200',longTermReservedCashMinor:'107'});});
 it('concentration/sector risk is deterministic and quote history contains only executions',async()=>{const f=await fixture();expect((await f.api('GET','/market/history/PTT')).body).toHaveLength(0);await f.order('BUY','26');const p=(await f.api('GET','/portfolio')).body;expect(p.risk.largestPositionBps).toBe(8695);expect(p.risk.warnings).toHaveLength(1);expect(p.risk.sectorExposure).toEqual([{sector:'Energy',weightBps:8695}]);expect((await f.api('GET','/market/history/PTT')).body).toHaveLength(1);});
 it('holding quantity tampering triggers reconciliation even if cash and aggregate cost match',async()=>{const f=await fixture();await f.order();const holding=(await f.api('GET','/portfolio/holdings')).body[0];await pool.query('UPDATE portfolio_holdings SET quantity=quantity+1 WHERE id=$1',[holding.id]);expect((await f.order()).body.error).toBe('RECONCILIATION_REQUIRED');});
 it('restart recovers holdings/cash from PostgreSQL; production exposes no test-price controls',async()=>{
  const f=await fixture();await f.order();
  async function start(mode:string){const child=spawn(process.execPath,[fileURLToPath(new URL('../../portfolio-service/dist/server.js',import.meta.url))],{env:{...process.env,NODE_ENV:mode,PORTFOLIO_PORT:'13007'},stdio:'ignore'});let ready=false;for(let i=0;i<40;i++){try{if((await fetch('http://127.0.0.1:13007/ready')).ok){ready=true;break;}}catch{}await new Promise(r=>setTimeout(r,50));}if(!ready){child.kill('SIGTERM');throw new Error('restart service unavailable');}return child;}
  const stop=(child:ReturnType<typeof spawn>)=>new Promise<void>(resolve=>{child.on('exit',()=>resolve());child.kill('SIGTERM');});
  let child=await start('development');let first:any;try{first=await fetch('http://127.0.0.1:13007/v1/portfolio',{headers:{authorization:`Bearer ${f.token}`}}).then(r=>r.json());}finally{await stop(child);}
  child=await start('production');try{const second=await fetch('http://127.0.0.1:13007/v1/portfolio',{headers:{authorization:`Bearer ${f.token}`}}).then(r=>r.json());expect(second.cashMinor).toBe(first.cashMinor);expect(second.holdings[0].id).toBe(first.holdings[0].id);expect(second.holdings[0].quantity).toBe('10.000000');expect((await fetch('http://127.0.0.1:13007/v1/market/test-scenario',{method:'PUT',headers:{authorization:`Bearer ${f.token}`,'content-type':'application/json'},body:JSON.stringify({symbol:'PTT',scenario:'up'})})).status).toBe(404);}finally{await stop(child);}
 },15000);

 it('fractional sell whose proceeds equal fee remains a balanced zero-net movement',async()=>{const f=await fixture();await f.order();await f.scenario('up');const sell=await f.order('SELL','0.084');expect(sell.status).toBe(201);expect(sell.body).toMatchObject({amount_minor:'1',fee_minor:'1',cost_minor:'0',realized_pnl_minor:'0'});expect((await f.api('GET','/portfolio')).body).toMatchObject({cashMinor:'199',costBasisMinor:'101',reconciliationStatus:'OK'});});

});
