import {baseApp,authenticate,audit,finish,HttpError} from '@tipkhun/auth';
import {pool,transaction} from '@tipkhun/database';
import {ensureLedgerAccounts,ledgerTransaction,lockOwner} from '@tipkhun/risk-data';
import {z} from 'zod';
const app=baseApp('allocation-service',async()=>{await pool.query('SELECT id FROM ledger_entries LIMIT 0');});
app.use('/v1',authenticate()); const uid=(res:any)=>res.locals.identity.id;
async function paper(c:any,id:string){const a=(await c.query("SELECT * FROM accounts WHERE user_id=$1 AND environment='paper'",[id])).rows[0];if(!a)throw new HttpError(409,'Start a paper account first');await ensureLedgerAccounts(c,id,a.id);return a;}
async function available(c:any,id:string){const r=(await c.query("SELECT coalesce(sum(CASE WHEN e.direction='CREDIT' THEN e.amount_minor ELSE -e.amount_minor END),0)::text AS n FROM ledger_entries e JOIN ledger_accounts a ON a.id=e.ledger_account_id WHERE a.user_id=$1 AND a.bucket='REALIZED_PROFIT'",[id])).rows[0];const n=BigInt(r.n);return n>0n?n:0n;}
async function settings(c:any,id:string){return (await c.query('SELECT * FROM allocation_settings WHERE user_id=$1',[id])).rows[0]??{short_term_bps:5000,long_term_bps:3000,withdrawal_bps:2000};}
app.get('/v1/allocations/settings',async(_q,res)=>res.json(await transaction(c=>c.query('SELECT short_term_bps AS "shortTermBps",long_term_bps AS "longTermBps",withdrawal_bps AS "withdrawalBps" FROM allocation_settings WHERE user_id=$1',[uid(res)]).then(x=>x.rows[0]??{shortTermBps:5000,longTermBps:3000,withdrawalBps:2000}))));
app.put('/v1/allocations/settings',async(req,res)=>{const d=z.object({shortTermBps:z.number().int().min(0).max(10000),longTermBps:z.number().int().min(0).max(10000),withdrawalBps:z.number().int().min(0).max(10000)}).refine(x=>x.shortTermBps+x.longTermBps+x.withdrawalBps===10000).parse(req.body);await transaction(c=>c.query('INSERT INTO allocation_settings(user_id,short_term_bps,long_term_bps,withdrawal_bps) VALUES($1,$2,$3,$4) ON CONFLICT(user_id) DO UPDATE SET short_term_bps=$2,long_term_bps=$3,withdrawal_bps=$4,updated_at=now()',[uid(res),d.shortTermBps,d.longTermBps,d.withdrawalBps]));res.json(d);});
app.get('/v1/allocations/available',async(_q,res)=>res.json({mode:'PAPER',availableMinor:(await transaction(c=>available(c,uid(res)))).toString()}));
app.post('/v1/allocations/preview',async(req,res)=>{const id=uid(res),availableAmount=await transaction(c=>available(c,id)),amount=req.body?.amountMinor?BigInt(String(req.body.amountMinor)):availableAmount;if(amount<0n||amount>availableAmount)throw new HttpError(409,'Requested amount exceeds available realized profit');const d=await transaction(async c=>{const s=await settings(c,id),short=amount*BigInt(s.short_term_bps)/10000n,long=amount*BigInt(s.long_term_bps)/10000n;return {mode:'PAPER',amountMinor:amount.toString(),shortTermMinor:short.toString(),longTermMinor:long.toString(),withdrawalMinor:(amount-short-long).toString()};});res.json(d);});
app.post('/v1/allocations/confirm',async(req,res)=>{const id=uid(res),key=String(req.header('idempotency-key')??'');if(!/^[A-Za-z0-9_.:-]{8,128}$/.test(key))throw new HttpError(400,'Idempotency-Key required');const result=await transaction(async c=>{await lockOwner(c,id);const a=await paper(c,id),old=(await c.query('SELECT * FROM allocation_batches WHERE user_id=$1 AND idempotency_key=$2',[id,key])).rows[0];if(old)return old;const amount=await available(c,id);if(amount<=0n)throw new HttpError(409,'No realized profit available');const s=await settings(c,id),short=amount*BigInt(s.short_term_bps)/10000n,long=amount*BigInt(s.long_term_bps)/10000n,withdrawal=amount-short-long,b=(await c.query('INSERT INTO allocation_batches(user_id,amount_minor,short_minor,long_minor,withdrawal_minor,idempotency_key) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[id,amount.toString(),short.toString(),long.toString(),withdrawal.toString(),key])).rows[0];const tx=await ledgerTransaction(c,id,a.id,'ALLOCATION_CONFIRMED',b.id,'allocation:'+b.id,[{bucket:'REALIZED_PROFIT',direction:'DEBIT',amount},{bucket:'TRADING_CAPITAL',direction:'CREDIT',amount:short},{bucket:'LONG_TERM_RESERVE',direction:'CREDIT',amount:long},{bucket:'WITHDRAWAL_RESERVE',direction:'CREDIT',amount:withdrawal}]);await c.query('UPDATE allocation_batches SET ledger_transaction_id=$2 WHERE id=$1',[b.id,tx]);await audit(c,id,'ALLOCATION_CONFIRMED','AllocationBatch',b.id,res.locals.requestId);return {...b,ledger_transaction_id:tx};});res.status(201).json(result);});
app.get('/v1/allocations/history',async(_q,res)=>res.json(await transaction(c=>c.query('SELECT * FROM allocation_batches WHERE user_id=$1 ORDER BY created_at DESC',[uid(res)]).then(x=>x.rows))));
app.get('/v1/allocations/:id',async(req,res)=>{const r=await transaction(c=>c.query('SELECT * FROM allocation_batches WHERE id=$1 AND user_id=$2',[req.params.id,uid(res)]).then(x=>x.rows[0]));if(!r)throw new HttpError(404,'Allocation not found');res.json(r);});
app.get('/v1/ledger/summary',async(_q,res)=>{const rows=await transaction(c=>c.query("SELECT a.bucket,coalesce(sum(CASE WHEN e.direction='CREDIT' THEN e.amount_minor ELSE -e.amount_minor END),0)::text AS amount FROM ledger_accounts a LEFT JOIN ledger_entries e ON e.ledger_account_id=a.id WHERE a.user_id=$1 GROUP BY a.bucket",[uid(res)]).then(x=>x.rows));res.json({mode:'PAPER',buckets:Object.fromEntries(rows.map((r:any)=>[r.bucket,r.amount]))});});
app.get('/v1/ledger/transactions',async(_q,res)=>res.json(await transaction(c=>c.query('SELECT * FROM ledger_transactions WHERE user_id=$1 ORDER BY created_at DESC LIMIT 200',[uid(res)]).then(x=>x.rows))));
app.get('/v1/notifications',async(_q,res)=>res.json(await pool.query('SELECT * FROM notifications WHERE user_id=$1 ORDER BY created_at DESC LIMIT 100',[uid(res)]).then(x=>x.rows)));
app.get('/v1/portfolio/cash',async(_q,res)=>{const r=await transaction(c=>c.query("SELECT coalesce(sum(CASE WHEN e.direction='CREDIT' THEN e.amount_minor ELSE -e.amount_minor END),0)::text AS n FROM ledger_entries e JOIN ledger_accounts a ON a.id=e.ledger_account_id WHERE a.user_id=$1 AND a.bucket='LONG_TERM_RESERVE'",[uid(res)]).then(x=>x.rows[0]));res.json({mode:'PAPER',longTermReservedCashMinor:r.n});});
app.get('/v1/withdrawals/reserve',async(_q,res)=>{const r=await transaction(c=>c.query("SELECT coalesce(sum(CASE WHEN e.direction='CREDIT' THEN e.amount_minor ELSE -e.amount_minor END),0)::text AS n FROM ledger_entries e JOIN ledger_accounts a ON a.id=e.ledger_account_id WHERE a.user_id=$1 AND a.bucket='WITHDRAWAL_RESERVE'",[uid(res)]).then(x=>x.rows[0]));res.json({mode:'PAPER',withdrawalReservedMinor:r.n});});
finish(app); if(process.env.NODE_ENV!=='test')app.listen(Number(process.env.ALLOCATION_PORT??3005)); export {app};
