import {afterEach,it,expect,vi} from 'vitest';
import {render,screen,fireEvent,cleanup} from '@testing-library/react';
import {PortfolioPage,money} from './PortfolioPage';
import {api} from './auth';
vi.mock('./auth',()=>({api:vi.fn()}));
const quote={priceMinor:'10',asOf:'2026-09-10T00:00:00Z',source:'fixture-paper',isDelayed:false,isStale:false};
const portfolio={cashMinor:'300',totalValueMinor:'300',realizedPnlMinor:'0',unrealizedPnlMinor:'0',returnBps:0,holdings:[],reconciliationStatus:'OK',targets:[],risk:{sectorExposure:[],warnings:[],cashBps:10000,drawdownBps:0}};
function setup(){vi.mocked(api).mockImplementation(async(path)=>{if(path==='/portfolio')return portfolio;if(path==='/portfolio/cash')return {cashMinor:'300',longTermReservedCashMinor:'7'};if(path==='/market/assets')return [{symbol:'PTT',name:'PTT PUBLIC COMPANY LIMITED'}];if(path==='/portfolio/orders/preview')return {quote,amountMinor:'10',feeMinor:'1',estimatedTotalMinor:'11',cashAfterMinor:'289',weightAfterBps:334};return [];});}
afterEach(()=>{cleanup();vi.resetAllMocks();});
it('loads honest empty holdings and server values without inventing a chart',async()=>{setup();render(<PortfolioPage/>);expect(await screen.findByText('ยังไม่มีสินทรัพย์ใน Portfolio')).toBeTruthy();expect(screen.getByTestId('Portfolio Cash').textContent).toBe('3.00 THB');expect(screen.queryByRole('img')).toBeNull();});
it('preview precedes mutation and changed quantity invalidates it',async()=>{setup();render(<PortfolioPage/>);await screen.findByText('ยังไม่มีสินทรัพย์ใน Portfolio');fireEvent.click(screen.getByRole('button',{name:'Preview order'}));await screen.findByLabelText('Order preview');expect(vi.mocked(api).mock.calls.some(c=>c[0]==='/portfolio/orders')).toBe(false);fireEvent.change(screen.getByLabelText('Quantity'),{target:{value:'2'}});expect(screen.queryByRole('button',{name:'Confirm paper order'})).toBeNull();});
it('confirm uses server endpoint, precise quantity and idempotency key',async()=>{setup();render(<PortfolioPage/>);await screen.findByText('ยังไม่มีสินทรัพย์ใน Portfolio');fireEvent.click(screen.getByRole('button',{name:'Preview order'}));fireEvent.click(await screen.findByRole('button',{name:'Confirm paper order'}));await screen.findByText('Paper BUY filled');const call=vi.mocked(api).mock.calls.find(c=>c[0]==='/portfolio/orders')!;expect(JSON.parse(call[1]!.body as string)).toEqual({side:'BUY',symbol:'PTT',quantity:'1'});expect((call[1]!.headers as Record<string,string>)['Idempotency-Key']).toMatch(/^[a-f0-9]{32}$/);});
it('backend failure is explicit and money formatting preserves large integers',async()=>{vi.mocked(api).mockRejectedValue(new Error('MARKET_DATA_UNAVAILABLE'));render(<PortfolioPage/>);expect((await screen.findByRole('alert')).textContent).toContain('MARKET_DATA_UNAVAILABLE');expect(money('900719925474099312')).toBe('9007199254740993.12 THB');});
