import {useEffect,useState} from 'react';
import {api} from './auth';
type Quote={priceMinor:string;asOf:string;source:string;isDelayed:boolean;isStale:boolean};
type Holding={id:string;symbol:string;name:string;quantity:string;averageCostMinor:string;marketValueMinor:string;unrealizedPnlMinor:string;weightBps:number;quote:Quote};
type Portfolio={cashMinor:string;totalValueMinor:string;realizedPnlMinor:string;unrealizedPnlMinor:string;returnBps:number;holdings:Holding[];reconciliationStatus:string;targets:{target:string;weightBps:number;currentBps:number;differenceBps:number}[];risk:{sectorExposure:{sector:string;weightBps:number}[];warnings:string[];cashBps:number;drawdownBps:number}};
type Cash={cashMinor:string;longTermReservedCashMinor:string};
type Snapshot={id:string;total_value_minor:string;created_at:string};
type Preview={quote:Quote;amountMinor:string;feeMinor:string;estimatedTotalMinor:string;cashAfterMinor:string;weightAfterBps:number};
// Formatting only. Financial values and percentages come from the server.
export function money(value:string){const n=BigInt(value),a=n<0n?-n:n;return `${n<0n?'-':''}${a/100n}.${(a%100n).toString().padStart(2,'0')} THB`;}
const newKey=()=>Array.from(crypto.getRandomValues(new Uint8Array(16)),n=>n.toString(16).padStart(2,'0')).join('');
export function PortfolioPage(){
 const [p,setP]=useState<Portfolio|null>(null),[cash,setCash]=useState<Cash|null>(null),[snapshots,setSnapshots]=useState<Snapshot[]>([]),[assets,setAssets]=useState<{symbol:string;name:string}[]>([]),[watch,setWatch]=useState<{symbol:string;quote:Quote}[]>([]);
 const [error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[amount,setAmount]=useState(''),[fundPreview,setFundPreview]=useState(false),[symbol,setSymbol]=useState('PTT'),[side,setSide]=useState('BUY'),[qty,setQty]=useState('1'),[preview,setPreview]=useState<Preview|null>(null),[orderKey,setOrderKey]=useState(''),[fundKey,setFundKey]=useState(''),[targetStock,setTargetStock]=useState('6000'),[targetEtf,setTargetEtf]=useState('3000'),[targetCash,setTargetCash]=useState('1000');
 async function load(){const [v,c,s,a,w]=await Promise.all([api<Portfolio>('/portfolio'),api<Cash>('/portfolio/cash'),api<Snapshot[]>('/portfolio/performance'),api<{symbol:string;name:string}[]>('/market/assets'),api<{symbol:string;quote:Quote}[]>('/watchlist')]);setP(v);setCash(c);setSnapshots(s);setAssets(a);setWatch(w);if(v.targets.length){setTargetStock(String(v.targets.find(t=>t.target==='PTT')?.weightBps??0));setTargetEtf(String(v.targets.find(t=>t.target==='TDEX')?.weightBps??0));setTargetCash(String(v.targets.find(t=>t.target==='CASH')?.weightBps??0));}}
 useEffect(()=>{load().catch(e=>setError(e.message));},[]);
 async function run(fn:()=>Promise<void>){setBusy(true);setError('');setMessage('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const post=(path:string,body:unknown,key?:string)=>api(path,{method:'POST',body:JSON.stringify(body),headers:key?{'Idempotency-Key':key}:undefined});
 const invalidate=()=>{setPreview(null);setOrderKey('');};
 return <section className="portfolio-page"><header><p className="eyebrow">SIMULATION / PAPER · Live Trading LOCKED</p><h1>Long-Term Portfolio</h1><p>ราคาสังเคราะห์จาก Server สำหรับทดลองเท่านั้น · ไม่มีข้อมูลราคาตลาดจริง</p></header>
 {error&&<p role="alert">{error} <button onClick={()=>run(load)}>ลองใหม่</button></p>}{message&&<p role="status">{message}</p>}
 {!p&&!error&&<p role="status">กำลังโหลด Portfolio…</p>}
 {p&&<><div className="portfolio-metrics">{[['Portfolio Value',p.totalValueMinor],['Portfolio Cash',p.cashMinor],['Long-Term Reserve Available',cash?.longTermReservedCashMinor??'0'],['Realized P&L',p.realizedPnlMinor],['Unrealized P&L',p.unrealizedPnlMinor]].map(([label,value])=><article className="panel" key={label}><small>{label}</small><h2 data-testid={label}>{money(value)}</h2></article>)}<article className="panel"><small>Total Return</small><h2>{p.returnBps/100}%</h2><small>Funding-adjusted drawdown: {p.risk.drawdownBps/100}%</small></article></div>
 {p.reconciliationStatus!=='OK'&&<p role="alert">RECONCILIATION_REQUIRED — พบบัญชีไม่ตรงกัน การซื้อขายและ funding ถูกระงับ</p>}
 <div className="portfolio-columns"><section className="panel"><h2>Fund Portfolio</h2><p>โอนจาก Long-Term Reserve เท่านั้น</p><label>Funding amount (minor units)<input aria-label="Funding amount (minor units)" value={amount} inputMode="numeric" onChange={e=>{setAmount(e.target.value);setFundPreview(false);setFundKey('');}}/></label><button disabled={busy||!/^\d+$/.test(amount)||BigInt(amount||'0')<=0n||BigInt(amount||'0')>BigInt(cash?.longTermReservedCashMinor??'0')} onClick={()=>{setFundPreview(true);setFundKey(newKey());}}>Preview funding</button>{fundPreview&&<div><p>Reserve → Portfolio Cash: {money(amount)}</p><button disabled={busy} onClick={()=>run(async()=>{await post('/portfolio/fund',{amountMinor:amount},fundKey);setFundPreview(false);await load();setMessage('Funded portfolio');})}>Confirm funding</button></div>}</section>
 <section className="panel"><h2>Paper BUY / SELL</h2><label>Side<select aria-label="Side" value={side} onChange={e=>{setSide(e.target.value);invalidate();}}><option>BUY</option><option>SELL</option></select></label><label>Asset<select aria-label="Asset" value={symbol} onChange={e=>{setSymbol(e.target.value);invalidate();}}>{assets.map(a=><option key={a.symbol} value={a.symbol}>{a.symbol} — {a.name}</option>)}</select></label><label>Quantity<input aria-label="Quantity" value={qty} onChange={e=>{setQty(e.target.value);invalidate();}}/></label><button disabled={busy} onClick={()=>run(async()=>{setPreview(await api<Preview>('/portfolio/orders/preview',{method:'POST',body:JSON.stringify({side,symbol,quantity:qty})}));setOrderKey(newKey());})}>Preview order</button>
 {preview&&<div aria-label="Order preview"><h3>{side} {symbol} · {qty}</h3><p>Price: {money(preview.quote.priceMinor)} · {preview.quote.source} · {preview.quote.asOf}</p><p>Estimated cost/proceeds: {money(preview.amountMinor)} · Fees: {money(preview.feeMinor)}</p><p>Cash after: {money(preview.cashAfterMinor)} · Weight after: {preview.weightAfterBps/100}%</p><p>Server ตรวจราคาและยอดอีกครั้งเมื่อยืนยัน ราคาอาจเปลี่ยนจาก Preview</p><button disabled={busy} onClick={()=>run(async()=>{await post('/portfolio/orders',{side,symbol,quantity:qty},orderKey);setPreview(null);await load();setMessage(`Paper ${side} filled`);})}>Confirm paper order</button></div>}</section></div>
 <section className="panel"><h2>Holdings</h2>{p.holdings.length===0?<p>ยังไม่มีสินทรัพย์ใน Portfolio</p>:<div className="table-scroll"><table><thead><tr>{['Symbol','Asset','Quantity','Average Cost','Current Price','Market Value','P&L','Weight'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{p.holdings.map(h=><tr key={h.id} data-testid={`holding-${h.symbol}`}><td>{h.symbol}</td><td>{h.name}<small>{h.quote.source} · {h.quote.asOf}{h.quote.isDelayed?' · Delayed':''}</small></td><td>{h.quantity}</td><td>{money(h.averageCostMinor)}</td><td>{money(h.quote.priceMinor)}</td><td>{money(h.marketValueMinor)}</td><td>{money(h.unrealizedPnlMinor)}</td><td>{h.weightBps/100}%</td></tr>)}</tbody></table></div>}</section>
 <div className="portfolio-columns"><section className="panel"><h2>Portfolio Performance</h2>{snapshots.length<2?<p>ต้องมี snapshot อย่างน้อย 2 จุดจากการใช้งานจริง</p>:<><svg viewBox="0 0 600 150" role="img" aria-label="Portfolio value snapshots"><polyline fill="none" stroke="currentColor" strokeWidth="2" points={(()=>{const vals=snapshots.map(s=>BigInt(s.total_value_minor)),min=vals.reduce((a,b)=>a<b?a:b),max=vals.reduce((a,b)=>a>b?a:b),range=max-min||1n;return vals.map((v,i)=>`${10+i*580/(vals.length-1)},${140-Number((v-min)*120n/range)}`).join(' ');})()}/></svg><small>มูลค่าจาก snapshot จริง รวมผลของการเติมเงิน · ล่าสุด {money(snapshots[snapshots.length-1].total_value_minor)}</small></>}</section><section className="panel"><h2>Allocation / Sector Exposure</h2>{[{symbol:'CASH',weightBps:p.risk.cashBps},...p.holdings].map(h=><div key={h.symbol}>{h.symbol}: {h.weightBps/100}%<meter min="0" max="10000" value={h.weightBps}/></div>)}{p.risk.sectorExposure.map(s=><p key={s.sector}>{s.sector}: {s.weightBps/100}%</p>)}{p.risk.warnings.map(w=><p role="alert" key={w}>{w}</p>)}</section></div>
 <section className="panel"><h2>Target Allocation</h2><p>Basis points: 10000 = 100% · ไม่มี auto rebalance</p>{[['Stock target',targetStock,setTargetStock],['ETF target',targetEtf,setTargetEtf],['Cash target',targetCash,setTargetCash]].map(([label,value,set])=><label key={String(label)}>{String(label)}<input aria-label={String(label)} value={String(value)} onChange={e=>(set as (v:string)=>void)(e.target.value)}/></label>)}<button disabled={busy} onClick={()=>run(async()=>{await api('/portfolio/targets',{method:'PUT',body:JSON.stringify({targets:[{target:'PTT',weightBps:Number(targetStock)},{target:'TDEX',weightBps:Number(targetEtf)},{target:'CASH',weightBps:Number(targetCash)}]})});await load();setMessage('Targets saved');})}>Save targets</button>{p.targets.map(t=><p key={t.target}>{t.target}: Target {t.weightBps/100}% · Current {t.currentBps/100}% · Difference {t.differenceBps/100}%</p>)}</section>
 <section className="panel"><h2>Watchlist</h2><button disabled={busy} onClick={()=>run(async()=>{await post('/watchlist',{symbol});await load();})}>Watch selected asset</button>{watch.length===0?<p>Watchlist ว่าง</p>:watch.map(w=><p key={w.symbol}>{w.symbol}: {money(w.quote.priceMinor)} · {w.quote.source} · {w.quote.asOf}<button disabled={busy} aria-label={`Remove ${w.symbol}`} onClick={()=>run(async()=>{await api(`/watchlist/${w.symbol}`,{method:'DELETE'});await load();})}>Remove</button></p>)}</section></>}
 </section>;
}
