import {chromium} from 'playwright';
import assert from 'node:assert/strict';
const base=process.env.WEB_TEST_URL??'http://localhost:5173';
const browser=await chromium.launch({headless:true});
try {
 const context=await browser.newContext();const page=await context.newPage(); page.on('response', r=>{if(r.url().includes('/auth/')||r.url().includes('/me')||r.url().includes('/bot')) console.log('HTTP',r.status(),r.url())}); page.on('requestfailed', r=>console.log('FAILED',r.url(),r.failure()?.errorText));
 const email=`browser-${Date.now()}@example.test`,password='Browser-test-password-123';
 await page.goto(`${base}/register`);
 await page.getByLabel('Email',{exact:true}).fill(email);
 await page.getByLabel('Password',{exact:true}).fill(password);
 await page.getByLabel('Confirm password',{exact:true}).fill(password);
 await page.getByRole('button',{name:'สมัครสมาชิก',exact:true}).click();
 await page.getByText('สร้างแผนความเสี่ยงแรกของคุณ').waitFor();
 await page.goto(`${base}/risk`);
 await page.getByLabel('riskTolerance',{exact:true}).fill('500');
 await page.getByLabel('dailyLossLimit',{exact:true}).fill('1750');
 await page.getByLabel('riskPerTrade',{exact:true}).fill('500');
 await page.getByLabel('maxPositions',{exact:true}).fill('2');
 await page.getByLabel('maxDrawdown',{exact:true}).fill('1000');
 await page.getByLabel('capitalMinor',{exact:true}).fill('35000');
 await page.getByLabel('dailyLossLimitMinor',{exact:true}).fill('1750');
 await page.getByLabel('riskPerTradeMinor',{exact:true}).fill('500');
 await page.getByRole('button',{name:'ดู Preview',exact:true}).click();
 await page.getByRole('button',{name:'ยืนยันบันทึก',exact:true}).click();
 console.log('after save', await page.locator('[role=status],[role=alert]').allTextContents());
 await page.getByText('บันทึกแล้ว',{exact:true}).waitFor();
 await page.reload();await page.getByText('Current Plan Version: 1',{exact:true}).waitFor();
 assert.equal(await page.getByLabel('capitalMinor',{exact:true}).inputValue(),'35000');
 await page.getByLabel('riskPerTradeMinor',{exact:true}).fill('400');
 await page.getByRole('button',{name:'ดู Preview',exact:true}).click();
 await page.getByRole('button',{name:'ยืนยันบันทึก',exact:true}).click();
 await page.getByText('บันทึกแล้ว',{exact:true}).waitFor();
 await page.reload();await page.getByText('Current Plan Version: 2',{exact:true}).waitFor();
 const cookies=await context.cookies();assert(cookies.some(c=>c.name==='tipkhun_refresh'&&c.httpOnly&&c.sameSite==='Strict'));
 assert.equal(await page.evaluate(()=>localStorage.length),0);
 await page.getByRole('button',{name:'Logout',exact:true}).click();
 await page.getByRole('heading',{name:'เข้าสู่ระบบ',exact:true}).waitFor();
 await page.goto(`${base}/dashboard`);
 await page.getByRole('heading',{name:'เข้าสู่ระบบ',exact:true}).waitFor();
 await page.getByLabel('Email',{exact:true}).fill(email);await page.getByLabel('Password',{exact:true}).fill(password);
 await page.getByRole('button',{name:'เข้าสู่ระบบ',exact:true}).click();
 await page.getByText('ภาพรวมการเงิน',{exact:true}).waitFor();await page.reload();
 await page.getByText('ภาพรวมการเงิน',{exact:true}).waitFor();
 await page.goto(`${base}/bot`); console.log('bot url', page.url(), 'body', (await page.locator('body').innerText()).slice(0,1000)); await page.getByText('Server-side Paper Trading · Live Trading: LOCKED',{exact:true}).waitFor();
 await page.getByRole('button',{name:'START',exact:true}).click(); await page.getByText('RUNNING',{exact:true}).waitFor();
 await page.getByRole('button',{name:'STOP',exact:true}).click(); await page.getByText('STOPPED',{exact:true}).waitFor();
 await page.screenshot({path:'/tmp/tipkhun-phase2-dashboard.png',fullPage:true});
 await page.getByRole('button',{name:'Logout',exact:true}).click();await page.getByRole('heading',{name:'เข้าสู่ระบบ',exact:true}).waitFor();
 console.log('PASS: real React register/login/dashboard, risk save/version/reload, HttpOnly refresh, protected logout and browser refresh');
} finally {await browser.close();}
