import {chromium} from 'playwright';
import assert from 'node:assert/strict';
const base=process.env.WEB_TEST_URL??'http://localhost:5173';
const browser=await chromium.launch({headless:true});
try {
 const context=await browser.newContext();const page=await context.newPage();
 const email=`browser-${Date.now()}@example.test`,password='Browser-test-password-123';
 await page.goto(`${base}/register`);
 await page.getByLabel('Email',{exact:true}).fill(email);
 await page.getByLabel('Password',{exact:true}).fill(password);
 await page.getByLabel('Confirm password',{exact:true}).fill(password);
 await page.getByRole('button',{name:'สมัครสมาชิก',exact:true}).click();
 await page.getByText('สร้างแผนความเสี่ยงแรกของคุณ').waitFor();
 await page.goto(`${base}/risk`);
 await page.getByLabel('riskTolerance',{exact:true}).fill('500');
 await page.getByLabel('dailyLossLimit',{exact:true}).fill('1750');
 await page.getByLabel('riskPerTrade',{exact:true}).fill('500');
 await page.getByLabel('maxPositions',{exact:true}).fill('2');
 await page.getByLabel('maxDrawdown',{exact:true}).fill('1000');
 await page.getByLabel('capitalMinor',{exact:true}).fill('35000');
 await page.getByLabel('dailyLossLimitMinor',{exact:true}).fill('1750');
 await page.getByLabel('riskPerTradeMinor',{exact:true}).fill('500');
 await page.getByRole('button',{name:'ดู Preview',exact:true}).click();
 await page.getByRole('button',{name:'ยืนยันบันทึก',exact:true}).click();
 await page.getByText('บันทึกแล้ว',{exact:true}).waitFor();
 await page.reload();await page.getByText('Current Plan Version: 1',{exact:true}).waitFor();
 assert.equal(await page.getByLabel('capitalMinor',{exact:true}).inputValue(),'35000');
 await page.getByLabel('riskPerTradeMinor',{exact:true}).fill('400');
 await page.getByRole('button',{name:'ดู Preview',exact:true}).click();
 await page.getByRole('button',{name:'ยืนยันบันทึก',exact:true}).click();
 await page.getByText('บันทึกแล้ว',{exact:true}).waitFor();
 await page.reload();await page.getByText('Current Plan Version: 2',{exact:true}).waitFor();
 const cookies=await context.cookies();assert(cookies.some(c=>c.name==='tipkhun_refresh'&&c.httpOnly&&c.sameSite==='Strict'));
 assert.equal(await page.evaluate(()=>localStorage.length),0);
 await page.getByRole('button',{name:'Logout',exact:true}).click();
 await page.getByRole('heading',{name:'เข้าสู่ระบบ',exact:true}).waitFor();
 await page.goto(`${base}/dashboard`);
 await page.getByRole('heading',{name:'เข้าสู่ระบบ',exact:true}).waitFor();
 await page.getByLabel('Email',{exact:true}).fill(email);await page.getByLabel('Password',{exact:true}).fill(password);
 const loginResponse=page.waitForResponse(r=>r.url().includes('/api/v1/auth/login')&&r.status()===200); await page.getByRole('button',{name:'เข้าสู่ระบบ',exact:true}).click(); const loginBody=await (await loginResponse).json(); const accessToken=loginBody.accessToken;
 await page.getByText('ภาพรวมการเงิน',{exact:true}).waitFor();await page.reload();
 await page.getByText('ภาพรวมการเงิน',{exact:true}).waitFor();
 await page.goto(`${base}/bot`); await page.getByText('Server-side Paper Trading · Live Trading: LOCKED',{exact:true}).waitFor();
 await page.getByRole('button',{name:'START',exact:true}).click(); await page.getByText('RUNNING',{exact:true}).waitFor();
 await page.getByRole('button',{name:'STOP',exact:true}).click(); await page.getByText('STOPPED',{exact:true}).waitFor();
 await page.getByRole('button',{name:'START',exact:true}).click(); await page.getByText('RUNNING',{exact:true}).waitFor();
 const profitable=await page.evaluate(async token=>{const h={'content-type':'application/json',authorization:`Bearer ${token}`,'Idempotency-Key':`browser-profit-${Date.now()}`};const o=await fetch('/api/v1/orders',{method:'POST',headers:h,body:JSON.stringify({instrument:'SYNTHETIC-THB',quantity:'1',type:'MARKET',scenario:'profit'})}).then(r=>r.json());const p=await fetch('/api/v1/positions',{headers:{authorization:`Bearer ${token}`}}).then(r=>r.json());const t=await fetch(`/api/v1/positions/${p[0].id}/close`,{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:'{}'}).then(r=>r.json());return {o,t};},accessToken); assert.equal(profitable.t.net_pnl_minor,'17');
 await page.goto(`${base}/profit-router`); await page.getByText('Profit Router',{exact:true}).waitFor(); await page.getByRole('button',{name:'PREVIEW',exact:true}).click(); await page.getByText('17',{exact:true}).waitFor(); await page.getByRole('button',{name:'CONFIRM',exact:true}).click(); await page.getByText('ยืนยันการจัดสรรแล้ว',{exact:true}).waitFor();
 await page.screenshot({path:'/tmp/tipkhun-phase2-dashboard.png',fullPage:true});
 await page.getByRole('button',{name:'Logout',exact:true}).click();await page.getByRole('heading',{name:'เข้าสู่ระบบ',exact:true}).waitFor();
 console.log('PASS: real React register/login/dashboard, risk save/version/reload, HttpOnly refresh, protected logout and browser refresh');
} finally {await browser.close();}
