CREATE OR REPLACE FUNCTION validate_paper_order_transition() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF NOT NEW.paper_order OR NEW.state=OLD.state THEN RETURN NEW; END IF;
 IF (OLD.state='UNKNOWN' AND NEW.state IN ('CANCELLED','FILLED','PARTIALLY_FILLED')) THEN RETURN NEW; END IF;
 IF (OLD.state='CREATED' AND NEW.state IN ('RISK_CHECKED','REJECTED')) OR
 (OLD.state='RISK_CHECKED' AND NEW.state IN ('SUBMITTED','REJECTED','CANCELLED')) OR
 (OLD.state='SUBMITTED' AND NEW.state IN ('ACKNOWLEDGED','REJECTED','UNKNOWN')) OR
 (OLD.state='ACKNOWLEDGED' AND NEW.state IN ('PARTIALLY_FILLED','FILLED','REJECTED','CANCELLED','UNKNOWN','EXPIRED')) OR
 (OLD.state='PARTIALLY_FILLED' AND NEW.state IN ('FILLED','CANCELLED','UNKNOWN','EXPIRED')) OR
 (OLD.state='FILLED' AND NEW.state='CLOSED') OR
 (OLD.state IN ('CANCELLED','EXPIRED') AND NEW.state='CLOSED' AND OLD.filled_quantity>0)
 THEN RETURN NEW; END IF;
 RAISE EXCEPTION 'Invalid paper order transition: % -> %',OLD.state,NEW.state;
END $$;
